version: '3'
services:
  mongo:
    image: 'mongo'
    container_name: mongo
    volumes:
      - /home/nick/docker-volumes/ExerciseTracker/mongo-volume/:/data/db
    ports:
      - "27017-27019:27017-27019"